spring.application.name=sherbrooke-university
# ===============================
# Configuration du serveur
# ===============================
server.port=8080

# =====================================================
# ======== CONFIGURATION ACTIVE : MYSQL ===============
# =====================================================

# ===============================
# Configuration MySQL Database
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/sherbrook_university_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate (MySQL)
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# =====================================================
# ======== SWAGGER / OPENAPI ==========================
# =====================================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha